# Generated by Django 2.1.7 on 2020-10-20 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_service'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Service',
            new_name='User',
        ),
    ]
