# Generated by Django 2.1.7 on 2020-10-20 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20201020_1029'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Service',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='firstName',
            new_name='firstname',
        ),
    ]
